[platformio]
default_envs = personal_hub
src_dir = ../platformio/src
data_dir = ../platformio/data
boards_dir = ../../boards

[env:personal_hub]
platform = espressif32@6.12.0
board = heltec_wireless_tracker_v2
framework = arduino
lib_extra_dirs = ../../shared/lib
extra_scripts = pre:build_config.py
board_build.filesystem = littlefs
board_build.flash_mode = dio
board_build.flash_size = 8MB
build_flags =
    -DUSE_FREERTOS=1
    -I../platformio/include
monitor_speed = 115200
lib_deps =
    jgromes/RadioLib@7.1.2
    bblanchon/ArduinoJson@7.4.3
    mikalhart/TinyGPSPlus@1.1.0
