(part "RAK4630"
    (packageRef "RAK4630")
    (interface
        (port "1" (symbPinId 1) (portName "VBUS") (portType INOUT))
        (port "2" (symbPinId 2) (portName "USB-") (portType INOUT))
        (port "3" (symbPinId 3) (portName "USB+") (portType INOUT))
        (port "4" (symbPinId 4) (portName "P0.13/I2C_SDA") (portType INOUT))
        (port "5" (symbPinId 5) (portName "P0.14/I2C_SCL") (portType INOUT))
        (port "6" (symbPinId 6) (portName "P0.15/UART2_RX") (portType INOUT))
        (port "7" (symbPinId 7) (portName "P0.16/UART2_TX") (portType INOUT))
        (port "8" (symbPinId 8) (portName "P0.17/UART2_DE") (portType INOUT))
        (port "9" (symbPinId 9) (portName "P0.19/UART1_RX_(AT_COMMAND)") (portType INOUT))
        (port "10" (symbPinId 10) (portName "P0.20/UART1_TX_(AT_COMMAND)") (portType INOUT))
        (port "11" (symbPinId 11) (portName "P0.21/UART1_DE") (portType INOUT))
        (port "12" (symbPinId 12) (portName "P0.10/NFC2") (portType INOUT))
        (port "13" (symbPinId 13) (portName "P0.09/NFC1") (portType INOUT))
        (port "14" (symbPinId 14) (portName "GND_1") (portType INOUT))
        (port "15" (symbPinId 15) (portName "RF_BT") (portType INOUT))
        (port "16" (symbPinId 16) (portName "GND_2") (portType INOUT))
        (port "17" (symbPinId 17) (portName "NRF_RESET") (portType INOUT))
        (port "18" (symbPinId 18) (portName "SWDCLK") (portType INOUT))
        (port "19" (symbPinId 19) (portName "SWDIO") (portType INOUT))
        (port "20" (symbPinId 20) (portName "VBAT_SX") (portType INOUT))
        (port "21" (symbPinId 21) (portName "VBAT_IO_SX") (portType INOUT))
        (port "22" (symbPinId 22) (portName "GND_3") (portType INOUT))
        (port "23" (symbPinId 23) (portName "P0.24/I2C_SDA_2") (portType INOUT))
        (port "24" (symbPinId 24) (portName "P0.25/I2C_SCL_2") (portType INOUT))
        (port "25" (symbPinId 25) (portName "P1.01/SW1") (portType INOUT))
        (port "26" (symbPinId 26) (portName "P1.02/SW2") (portType INOUT))
        (port "27" (symbPinId 27) (portName "P1.03/LED1") (portType INOUT))
        (port "28" (symbPinId 28) (portName "P1.04/LED2") (portType INOUT))
        (port "29" (symbPinId 29) (portName "P0.03/QSPI_CLK") (portType INOUT))
        (port "30" (symbPinId 30) (portName "P0.02/QSPI_DIO3") (portType INOUT))
        (port "31" (symbPinId 31) (portName "P0.28/QSPI_DIO2") (portType INOUT))
        (port "32" (symbPinId 32) (portName "P0.29/QSPI_DIO1") (portType INOUT))
        (port "33" (symbPinId 33) (portName "P0.30/QSPI_DIO0") (portType INOUT))
        (port "34" (symbPinId 34) (portName "P0.26/QSPI_CS") (portType INOUT))
        (port "35" (symbPinId 35) (portName "GND_4") (portType INOUT))
        (port "36" (symbPinId 36) (portName "GND_5") (portType INOUT))
        (port "37" (symbPinId 37) (portName "RF_LORA") (portType INOUT))
        (port "38" (symbPinId 38) (portName "GND_6") (portType INOUT))
        (port "39" (symbPinId 39) (portName "P0.31/AIN7") (portType INOUT))
        (port "40" (symbPinId 40) (portName "P0.05/AIN3") (portType INOUT))
        (port "41" (symbPinId 41) (portName "P0.04/AIN2") (portType INOUT))
        (port "42" (symbPinId 42) (portName "GND_7") (portType INOUT))
        (port "43" (symbPinId 43) (portName "VDD_NRF") (portType INOUT))
        (port "44" (symbPinId 44) (portName "VBAT_NRF") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "RAK")
    (property "Manufacturer_Part_Number" "RAK4630")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "RF IC Transceiver Bluetooth, LoRa 915MHz, 920MHz, 923MHz SPI Interface")
    (property "Datasheet_Link" "https://dl-docs.rakwireless.com/api/render/?emulateScreenMedia=false&pdf.format=legal&url=https%3A%2F%2Fdocs.rakwireless.com%2FProduct-Categories%2FWisDuo%2FRAK4630-Module%2FDatasheet%2F")
    (property "symbolName1" "RAK4630")
)
