(part "DMG2305UX-13"
    (packageRef "SOT96P240X120-3N")
    (interface
        (port "1" (symbPinId 1) (portName "G") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S") (portType INOUT))
        (port "3" (symbPinId 3) (portName "D") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "122")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "DMG2305UX-13")
    (property "Mouser_Part_Number" "621-DMG2305UX-13")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/DMG2305UX-13?qs=L1DZKBg7t5Hgw5KN3G2IRg%3D%3D")
    (property "Arrow_Part_Number" "DMG2305UX-13")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/dmg2305ux-13/diodes-incorporated.html?utm_currency=USD&region=nac")
    (property "Description" "MOSFET P-Ch 20V 5A Enhancement SOT23 Diodes Inc DMG2305UX-13 P-channel MOSFET Transistor, -3.3 A, -20 V, 3-Pin SOT-23")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/2/DMG2305UX-13.pdf")
    (property "symbolName1" "DMG2305UX-13")
)
