(part "SIM8055-6-1-14-01-A"
    (packageRef "SIM8055611401A")
    (interface
        (port "C1" (symbPinId 1) (portName "VCC") (portType INOUT))
        (port "C2" (symbPinId 2) (portName "RST") (portType INOUT))
        (port "C3" (symbPinId 3) (portName "CLK") (portType INOUT))
        (port "C5" (symbPinId 4) (portName "GND") (portType INOUT))
        (port "C6" (symbPinId 5) (portName "VPP") (portType INOUT))
        (port "C7" (symbPinId 6) (portName "I/O") (portType INOUT))
        (port "CD1" (symbPinId 7) (portName "CD") (portType INOUT))
        (port "MH1" (symbPinId 8) (portName "MH1") (portType INOUT))
        (port "MH2" (symbPinId 9) (portName "MH2") (portType INOUT))
        (port "MP1" (symbPinId 10) (portName "MP1") (portType INOUT))
        (port "MP2" (symbPinId 11) (portName "MP2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "GCT (GLOBAL CONNECTOR TECHNOLOGY)")
    (property "Manufacturer_Part_Number" "SIM8055-6-1-14-01-A")
    (property "Mouser_Part_Number" "640-SIM8055611401A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/GCT/SIM8055-6-1-14-01-A?qs=KUoIvG%2F9Ilbi5BaFCOA%2Fkg%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Memory Card Connectors Nano SIM Card Connector,Push-Pull Type, 6 PIN, SMT, with normally open card detection switch, Profile 1.35mm, with location post")
    (property "Datasheet_Link" "https://gct.co/connector/sim8055")
    (property "symbolName1" "SIM8055-6-1-14-01-A")
)
