(part "SM03B-SRSS-TB_LF__SN_"
    (packageRef "SM03BSRSSTBLFSN")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "MP1" (symbPinId 4) (portName "MP1") (portType INOUT))
        (port "MP2" (symbPinId 5) (portName "MP2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "JST (JAPAN SOLDERLESS TERMINALS)")
    (property "Manufacturer_Part_Number" "SM03B-SRSS-TB(LF)(SN)")
    (property "Mouser_Part_Number" "N/A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/JST-Commercial/SM03B-SRSS-TBLFSN?qs=IKkN%2F947nfBpJw20m79wuw%3D%3D")
    (property "Arrow_Part_Number" "SM03B-SRSS-TB(LF)(SN)")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/sm03b-srss-tb-lf-sn/jst-manufacturing.html?utm_currency=USD&region=europe")
    (property "Description" "Wire To Board / Wire To Wire Connector RoHS")
    (property "Datasheet_Link" "http://www.jst-mfg.com/product/pdf/eng/eSR.pdf")
    (property "symbolName1" "SM03B-SRSS-TB_LF__SN_")
)
