(part "ST4SI3M004600HFW"
    (packageRef "SON127P600X500X100-9N")
    (interface
        (port "1" (symbPinId 1) (portName "GND") (portType INOUT))
        (port "2" (symbPinId 2) (portName "SWIO") (portType INOUT))
        (port "3" (symbPinId 3) (portName "I/O") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC_1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "CLK") (portType INOUT))
        (port "7" (symbPinId 7) (portName "%RESET%") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VCC") (portType INOUT))
        (port "9" (symbPinId 9) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "ST4SI3M004600HFW")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "ST4SI3M004600HFW")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/st4si3m004600hfw/stmicroelectronics.html?utm_currency=USD&region=nac")
    (property "Description" "GSMA eSIM for IoT system on chip solution for IoT environment")
    (property "Datasheet_Link" "https://estore.st.com/en/st4si3m004600hfw-cpn.html")
    (property "symbolName1" "ST4SI3M004600HFW")
)
