(part "LQW03AW10NJ00D"
    (packageRef "LQW03AW10NJ00D")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "LQW03AW10NJ00D")
    (property "Mouser_Part_Number" "81-LQW03AW10NJ00D")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Electronics/LQW03AW10NJ00D?qs=5lbl9CW7Yx%2FLHUKnOlvV8g%3D%3D")
    (property "Arrow_Part_Number" "LQW03AW10NJ00D")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/lqw03aw10nj00d/murata-manufacturing?region=nac")
    (property "Description" "LQW03AW_00 Series Inductor 10nH +/-5% 0201 (0603)")
    (property "Datasheet_Link" "https://search.murata.co.jp/Ceramy/image/img/P02/JELF243A-0109.pdf")
    (property "symbolName1" "LQW03AW10NJ00D")
)
