(part "B3U-1000P"
    (packageRef "B3U-1000P")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "OMRON Electronics")
    (property "Manufacturer_Part_Number" "B3U-1000P")
    (property "Mouser_Part_Number" "653-B3U-1000P")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Omron-Electronics/B3U-1000P?qs=AO7BQMcsEu4ip80xyf2FwA%3D%3D")
    (property "Arrow_Part_Number" "B3U-1000P")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/b3u1000p/omron?utm_currency=USD&region=europe")
    (property "Description" "OMRON ELECTRONIC COMPONENTS - B3U-1000P - SWITCH, SPST-NO, 0.05A, 12V, SMD")
    (property "Datasheet_Link" "https://www.omron.com/ecb/products/pdf/en-b3u.pdf")
    (property "symbolName1" "B3U-1000P")
)
