(part "SKY65723-11"
    (packageRef "SKY6572311")
    (interface
        (port "1" (symbPinId 1) (portName "VCC") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VEN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "RF_IN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "N/C_1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "N/C_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "RF_OUT") (portType INOUT))
        (port "7" (symbPinId 7) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Skyworks")
    (property "Manufacturer_Part_Number" "SKY65723-11")
    (property "Mouser_Part_Number" "873-SKY65723-11")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Skyworks-Solutions-Inc/SKY65723-11?qs=amGC7iS6iy%2FBJl3G6X1IOw%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "RF Front End GPS GNSS LNA Module B13 Notch")
    (property "Datasheet_Link" "https://www.skyworksinc.com/-/media/SkyWorks/Documents/Products/2801-2900/SKY65723_11_203921F.pdf")
    (property "symbolName1" "SKY65723-11")
)
