#!/usr/bin/env python3
"""Convert the user-selected Home Hub PNG artwork into LVGL v9 C assets."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image


ALPHA_ICONS = {
    "home": ("home.png", 30),
    "rotate": ("rotate.png", 30),
    "night_mode": ("night-mode.png", 30),
    "brightness": ("brightness.png", 30),
    "zoom_in": ("zoom-in.png", 30),
    "zoom_out": ("zoom-out.png", 30),
    "settings": ("settings.png", 64),
    "diagnostic": ("diagnostic.png", 64),
}
COLOUR_ICONS = {"map": ("map.png", 72)}


def fitted_rgba(path: Path, size: int) -> Image.Image:
    image = Image.open(path).convert("RGBA")
    alpha = image.getchannel("A")
    bounds = alpha.getbbox()
    if bounds is None:
        raise ValueError(f"{path} has no visible pixels")
    image = image.crop(bounds)
    inner = max(1, int(size * 0.90))
    image.thumbnail((inner, inner), Image.Resampling.LANCZOS)
    output = Image.new("RGBA", (size, size))
    output.alpha_composite(image, ((size - image.width) // 2, (size - image.height) // 2))
    return output


def bytes_as_cpp(data: bytes) -> str:
    lines = []
    for offset in range(0, len(data), 16):
        chunk = data[offset : offset + 16]
        lines.append("    " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    return "\n".join(lines)


def descriptor(name: str, size: int, colour_format: str, data_size: int, stride: int) -> str:
    return f"""const lv_image_dsc_t icon_{name} = {{
    .header = {{
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = {colour_format},
        .flags = 0,
        .w = {size},
        .h = {size},
        .stride = {stride},
        .reserved_2 = 0,
    }},
    .data_size = {data_size},
    .data = icon_{name}_data,
    .reserved = nullptr,
    .reserved_2 = nullptr,
}};
"""


def generate(source: Path, output: Path) -> None:
    declarations = []
    definitions = []

    for name, (filename, size) in ALPHA_ICONS.items():
        image = fitted_rgba(source / filename, size)
        data = image.getchannel("A").tobytes()
        declarations.append(f"extern const lv_image_dsc_t icon_{name};")
        definitions.append(
            f"alignas(4) static const uint8_t icon_{name}_data[] = {{\n"
            f"{bytes_as_cpp(data)}\n}};\n\n"
            + descriptor(name, size, "LV_COLOR_FORMAT_A8", len(data), size)
        )

    for name, (filename, size) in COLOUR_ICONS.items():
        image = fitted_rgba(source / filename, size)
        data = bytearray()
        rgba = image.tobytes()
        for offset in range(0, len(rgba), 4):
            red, green, blue, alpha = rgba[offset : offset + 4]
            data.extend((blue, green, red, alpha))
        declarations.append(f"extern const lv_image_dsc_t icon_{name};")
        definitions.append(
            f"alignas(4) static const uint8_t icon_{name}_data[] = {{\n"
            f"{bytes_as_cpp(bytes(data))}\n}};\n\n"
            + descriptor(name, size, "LV_COLOR_FORMAT_ARGB8888", len(data), size * 4)
        )

    header = """#pragma once

#include "lvgl.h"

namespace bluepaws::ui {

""" + "\n".join(declarations) + "\n\n}  // namespace bluepaws::ui\n"
    source_text = """// Generated by tools/build_home_hub_icons.py. Do not edit by hand.
#include "ui_icons.h"

#include <cstdint>

namespace bluepaws::ui {

""" + "\n".join(definitions) + "\n}  // namespace bluepaws::ui\n"

    output.mkdir(parents=True, exist_ok=True)
    (output / "ui_icons.h").write_text(header, encoding="utf-8", newline="\n")
    (output / "ui_icons.cpp").write_text(source_text, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        type=Path,
        default=Path("home-hub/firmware/assets/icons"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("home-hub/firmware/main"),
    )
    args = parser.parse_args()
    generate(args.source.resolve(), args.output.resolve())


if __name__ == "__main__":
    main()
