#!/usr/bin/env python3
"""Convert the user-selected Home Hub PNG artwork into LVGL v9 C assets."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image


ALPHA_ICONS = {
    "home": ("home.png", 30),
    "rotate": ("rotate.png", 30),
    "night_mode": ("night-mode.png", 30),
    "brightness": ("brightness.png", 30),
    "zoom_in": ("zoom-in.png", 30),
    "zoom_out": ("zoom-out.png", 30),
    "settings": ("settings.png", 64),
    "diagnostic": ("diagnostic.png", 64),
}
COLOUR_ICONS = {
    "map": ("map.png", (72, 72)),
    "status_normal": ("status-normal.png", (74, 22)),
    "status_at_home": ("status-at-home.png", (84, 22)),
    "status_out": ("status-out.png", (58, 22)),
    "profile_powersave": ("profile-powersave.png", (104, 20)),
    "status_error": ("status-error.png", (82, 20)),
    "radio_wifi": ("radio-wifi.png", (28, 20)),
    "radio_4g": ("radio-4g.png", (28, 20)),
    "radio_rf": ("radio-rf.png", (28, 20)),
    "signal_full": ("signal-full.png", (22, 18)),
    "signal_high": ("signal-high.png", (22, 18)),
    "signal_medium": ("signal-medium.png", (22, 18)),
    "signal_low": ("signal-low.png", (22, 18)),
    "signal_mobile": ("signal-mobile.png", (22, 18)),
    "radio_antenna": ("radio-antenna.png", (20, 20)),
    "battery_full": ("battery-full.png", (26, 18)),
    "battery_medium": ("battery-medium.png", (26, 18)),
    "battery_low": ("battery-low.png", (26, 18)),
    "battery_error": ("battery-error.png", (26, 18)),
    "status_home_small": ("status-home.png", (18, 18)),
    "status_stopwatch": ("status-stopwatch.png", (18, 18)),
}


def fitted_rgba(path: Path, width: int, height: int | None = None) -> Image.Image:
    height = width if height is None else height
    image = Image.open(path).convert("RGBA")
    alpha = image.getchannel("A")
    bounds = alpha.getbbox()
    if bounds is None:
        raise ValueError(f"{path} has no visible pixels")
    image = image.crop(bounds)
    inner_width = max(1, int(width * 0.94))
    inner_height = max(1, int(height * 0.94))
    image.thumbnail((inner_width, inner_height), Image.Resampling.LANCZOS)
    output = Image.new("RGBA", (width, height))
    output.alpha_composite(image, ((width - image.width) // 2, (height - image.height) // 2))
    return output


def bytes_as_cpp(data: bytes) -> str:
    lines = []
    for offset in range(0, len(data), 16):
        chunk = data[offset : offset + 16]
        lines.append("    " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    return "\n".join(lines)


def descriptor(
    name: str, width: int, height: int, colour_format: str, data_size: int, stride: int
) -> str:
    return f"""const lv_image_dsc_t icon_{name} = {{
    .header = {{
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = {colour_format},
        .flags = 0,
        .w = {width},
        .h = {height},
        .stride = {stride},
        .reserved_2 = 0,
    }},
    .data_size = {data_size},
    .data = icon_{name}_data,
    .reserved = nullptr,
    .reserved_2 = nullptr,
}};
"""


def generate(source: Path, output: Path) -> None:
    declarations = []
    definitions = []

    for name, (filename, size) in ALPHA_ICONS.items():
        image = fitted_rgba(source / filename, size)
        data = image.getchannel("A").tobytes()
        declarations.append(f"extern const lv_image_dsc_t icon_{name};")
        definitions.append(
            f"alignas(4) static const uint8_t icon_{name}_data[] = {{\n"
            f"{bytes_as_cpp(data)}\n}};\n\n"
            + descriptor(name, size, size, "LV_COLOR_FORMAT_A8", len(data), size)
        )

    for name, (filename, dimensions) in COLOUR_ICONS.items():
        width, height = dimensions
        image = fitted_rgba(source / filename, width, height)
        data = bytearray()
        rgba = image.tobytes()
        for offset in range(0, len(rgba), 4):
            red, green, blue, alpha = rgba[offset : offset + 4]
            data.extend((blue, green, red, alpha))
        declarations.append(f"extern const lv_image_dsc_t icon_{name};")
        definitions.append(
            f"alignas(4) static const uint8_t icon_{name}_data[] = {{\n"
            f"{bytes_as_cpp(bytes(data))}\n}};\n\n"
            + descriptor(
                name, width, height, "LV_COLOR_FORMAT_ARGB8888", len(data), width * 4
            )
        )

    header = """#pragma once

#include "lvgl.h"

namespace bluepaws::ui {

""" + "\n".join(declarations) + "\n\n}  // namespace bluepaws::ui\n"
    source_text = """// Generated by tools/build_home_hub_icons.py. Do not edit by hand.
#include "ui_icons.h"

#include <cstdint>

namespace bluepaws::ui {

""" + "\n".join(definitions) + "\n}  // namespace bluepaws::ui\n"

    output.mkdir(parents=True, exist_ok=True)
    (output / "ui_icons.h").write_text(header, encoding="utf-8", newline="\n")
    (output / "ui_icons.cpp").write_text(source_text, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        type=Path,
        default=Path("home-hub/firmware/assets/icons"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("home-hub/firmware/main"),
    )
    args = parser.parse_args()
    generate(args.source.resolve(), args.output.resolve())


if __name__ == "__main__":
    main()
