#!/usr/bin/env python3
"""Generate private Bluepaws simulator credentials and matching provisioning SQL.

The JSON output contains plaintext test credentials and must stay off Git.  The
SQL output contains only bearer-token hashes, but it includes the HMAC values
once so Supabase Vault can encrypt them.  Treat both files as secrets.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import secrets
import stat
import sys
import uuid
from dataclasses import dataclass
from pathlib import Path


MAX_DEVICE_ID = 65_535


@dataclass(frozen=True)
class GeneratedDevice:
    device_id: int
    bearer_token: str
    hmac_key_b64: str


@dataclass(frozen=True)
class GeneratedGateway:
    gateway_guid16: str
    display_name: str
    bearer_token: str


def generate_device(device_id: int) -> GeneratedDevice:
    if not 1 <= device_id <= MAX_DEVICE_ID:
        raise ValueError("device ID must be from 1 to 65535")
    return GeneratedDevice(
        device_id=device_id,
        bearer_token=secrets.token_urlsafe(32),
        hmac_key_b64=base64.b64encode(secrets.token_bytes(32)).decode("ascii"),
    )


def generate_gateway(gateway_guid16: str, display_name: str) -> GeneratedGateway:
    normalized = gateway_guid16.strip().upper()
    if len(normalized) != 4:
        raise ValueError("gateway GUID16 must be four hexadecimal characters")
    try:
        number = int(normalized, 16)
    except ValueError as error:
        raise ValueError("gateway GUID16 must be four hexadecimal characters") from error
    if not 1 <= number <= MAX_DEVICE_ID:
        raise ValueError("gateway GUID16 0000 is reserved")
    clean_name = display_name.strip()
    if not 1 <= len(clean_name) <= 80:
        raise ValueError("gateway display name must contain 1..80 characters")
    return GeneratedGateway(normalized, clean_name, secrets.token_urlsafe(32))


def credential_bundle(
    devices: list[GeneratedDevice], gateway: GeneratedGateway | None
) -> dict[str, object]:
    return {
        "schema_version": 1,
        "devices": [
            {
                "device_id": device.device_id,
                "bearer_token": device.bearer_token,
                "hmac_key_b64": device.hmac_key_b64,
            }
            for device in devices
        ],
        "gateways": (
            [
                {
                    "gateway_guid16": gateway.gateway_guid16,
                    "display_name": gateway.display_name,
                    "bearer_token": gateway.bearer_token,
                }
            ]
            if gateway is not None
            else []
        ),
    }


def provisioning_sql(
    devices: list[GeneratedDevice],
    household_id: uuid.UUID,
    key_version: int,
    gateway: GeneratedGateway | None,
) -> str:
    if not 1 <= key_version <= 32_767:
        raise ValueError("HMAC key version must be from 1 to 32767")
    household = str(household_id)
    lines = [
        "-- Generated by tools/generate_tlv_credentials.py.",
        "-- Contains plaintext HMAC material until Vault encrypts it.",
        "-- Run once in the Supabase SQL Editor, then securely delete this file.",
        "begin;",
        "",
    ]
    for device in devices:
        token_hash = hashlib.sha256(device.bearer_token.encode("utf-8")).hexdigest()
        secret_name = f"bluepaws-device-{device.device_id}-hmac-v{key_version}"
        lines.extend(
            [
                "insert into public.devices (device_id, household_id, display_name, enabled)",
                (
                    f"values ({device.device_id}, '{household}'::uuid, "
                    f"'Device {device.device_id}', true)"
                ),
                "on conflict (device_id) do update",
                "set enabled = true;",
                "",
                (
                    "insert into public.device_ingest_credentials "
                    "(device_id, token_hash, enabled, rotated_at)"
                ),
                f"values ({device.device_id}, '{token_hash}', true, now())",
                "on conflict (device_id) do update",
                "set token_hash = excluded.token_hash, enabled = true, rotated_at = now();",
                "",
                "with new_secret as (",
                "  select vault.create_secret(",
                f"    '{device.hmac_key_b64}',",
                f"    '{secret_name}',",
                f"    'Bluepaws TLV HMAC key for device {device.device_id}, version {key_version}'",
                "  ) as vault_secret_id",
                ")",
                "insert into public.device_hmac_keys (device_id, key_version, vault_secret_id)",
                f"select {device.device_id}, {key_version}, vault_secret_id from new_secret;",
                "",
            ]
        )
    if gateway is not None:
        gateway_number = int(gateway.gateway_guid16, 16)
        gateway_hash = hashlib.sha256(gateway.bearer_token.encode("utf-8")).hexdigest()
        escaped_name = gateway.display_name.replace("'", "''")
        lines.extend(
            [
                "insert into public.gateways (gateway_guid16, household_id, display_name, enabled)",
                f"values ({gateway_number}, '{household}'::uuid, '{escaped_name}', true)",
                "on conflict (gateway_guid16) do update",
                "set display_name = excluded.display_name,",
                "    enabled = true;",
                "",
                (
                    "insert into public.gateway_ingest_credentials "
                    "(gateway_guid16, token_hash, enabled, rotated_at)"
                ),
                f"values ({gateway_number}, '{gateway_hash}', true, now())",
                "on conflict (gateway_guid16) do update",
                "set token_hash = excluded.token_hash, enabled = true, rotated_at = now();",
                "",
            ]
        )
    lines.extend(["commit;", ""])
    return "\n".join(lines)


def private_write(path: Path, content: str, *, overwrite: bool) -> None:
    path = path.expanduser().resolve()
    path.parent.mkdir(parents=True, exist_ok=True)
    flags = os.O_WRONLY | os.O_CREAT
    flags |= os.O_TRUNC if overwrite else os.O_EXCL
    descriptor = os.open(path, flags, stat.S_IRUSR | stat.S_IWUSR)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
    except BaseException:
        try:
            os.close(descriptor)
        except OSError:
            pass
        raise
    try:
        os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)
    except OSError:
        pass


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate secure Bluepaws test-device credentials and Supabase SQL."
    )
    parser.add_argument("--count", type=int, default=5, help="number of collars (default: 5)")
    parser.add_argument(
        "--start-device-id", type=int, default=1001, help="first 16-bit device ID"
    )
    parser.add_argument(
        "--household-id",
        "--family-id",
        dest="household_id",
        required=True,
        help="target Supabase Family/household UUID",
    )
    parser.add_argument("--key-version", type=int, default=1, help="HMAC key version")
    parser.add_argument(
        "--output", type=Path, default=Path("tools/devices.json"), help="private JSON output"
    )
    parser.add_argument(
        "--sql-output",
        type=Path,
        default=Path("tools/devices.provision.sql"),
        help="private Supabase SQL output",
    )
    parser.add_argument(
        "--gateway-guid16",
        help="optional four-character hexadecimal LoRa gateway ID, for example 0016",
    )
    parser.add_argument(
        "--gateway-name", default="Bluepaws Test Hub", help="optional gateway display name"
    )
    parser.add_argument("--force", action="store_true", help="replace existing output files")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        household_id = uuid.UUID(args.household_id)
        if not 1 <= args.count <= MAX_DEVICE_ID:
            raise ValueError("count must be from 1 to 65535")
        final_device_id = args.start_device_id + args.count - 1
        if not 1 <= args.start_device_id <= final_device_id <= MAX_DEVICE_ID:
            raise ValueError("generated device IDs must all fit in the range 1..65535")
        devices = [
            generate_device(device_id)
            for device_id in range(args.start_device_id, final_device_id + 1)
        ]
        gateway = (
            generate_gateway(args.gateway_guid16, args.gateway_name)
            if args.gateway_guid16
            else None
        )
        private_write(
            args.output,
            json.dumps(credential_bundle(devices, gateway), indent=2) + "\n",
            overwrite=args.force,
        )
        try:
            private_write(
                args.sql_output,
                provisioning_sql(devices, household_id, args.key_version, gateway),
                overwrite=args.force,
            )
        except BaseException:
            args.output.expanduser().resolve().unlink(missing_ok=True)
            raise
    except (OSError, ValueError) as error:
        print(f"Credential generation failed: {error}", file=sys.stderr)
        return 2

    gateway_note = f" plus gateway {gateway.gateway_guid16}" if gateway else ""
    print(f"Generated {len(devices)} device credential(s){gateway_note}.")
    print(f"Private simulator JSON: {args.output.expanduser().resolve()}")
    print(f"One-time Supabase SQL: {args.sql_output.expanduser().resolve()}")
    print("Run the SQL once, verify ingestion, then securely remove the SQL file.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
