-- Bluepaws cloud ingestion schema.
-- Device identifiers are unsigned 16-bit values on the wire. PostgreSQL has no
-- unsigned smallint, so the database uses integer plus an explicit range check.

create table if not exists public.positions (
  id bigint generated by default as identity primary key,
  device_uid integer not null,
  message_id integer not null,
  latitude double precision not null,
  longitude double precision not null,
  battery integer,
  source text not null default 'edge-api',
  recorded_at timestamptz not null default now(),
  received_at timestamptz not null default now(),
  schema_version smallint not null default 1
);

create table if not exists public.devices (
  device_id integer primary key,
  display_name text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  constraint devices_device_id_range check (device_id between 1 and 65534),
  constraint devices_display_name_length check (length(btrim(display_name)) between 1 and 80)
);

create table if not exists public.device_ingest_credentials (
  device_id integer primary key references public.devices(device_id) on delete cascade,
  token_hash text not null unique,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  rotated_at timestamptz,
  constraint device_ingest_credentials_token_hash_format
    check (token_hash ~ '^[0-9a-f]{64}$')
);

alter table public.positions add column if not exists received_at timestamptz;
alter table public.positions add column if not exists schema_version smallint;

update public.positions
set received_at = coalesce(received_at, recorded_at, now())
where received_at is null;

update public.positions
set recorded_at = received_at
where recorded_at is null;

update public.positions
set schema_version = 1
where schema_version is null;

update public.positions
set source = 'legacy'
where source is null;

alter table public.positions alter column received_at set default now();
alter table public.positions alter column received_at set not null;
alter table public.positions alter column recorded_at set default now();
alter table public.positions alter column recorded_at set not null;
alter table public.positions alter column schema_version set default 1;
alter table public.positions alter column schema_version set not null;
alter table public.positions alter column source set default 'edge-api';
alter table public.positions alter column source set not null;

insert into public.devices (device_id, display_name)
select distinct device_uid, 'Device ' || device_uid::text
from public.positions
where device_uid between 1 and 65534
on conflict (device_id) do nothing;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'positions_device_uid_range'
      and conrelid = 'public.positions'::regclass
  ) then
    alter table public.positions
      add constraint positions_device_uid_range
      check (device_uid between 1 and 65534);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'positions_message_id_nonnegative'
      and conrelid = 'public.positions'::regclass
  ) then
    alter table public.positions
      add constraint positions_message_id_nonnegative
      check (message_id between 0 and 2147483647);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'positions_latitude_range'
      and conrelid = 'public.positions'::regclass
  ) then
    alter table public.positions
      add constraint positions_latitude_range
      check (latitude between -90 and 90);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'positions_longitude_range'
      and conrelid = 'public.positions'::regclass
  ) then
    alter table public.positions
      add constraint positions_longitude_range
      check (longitude between -180 and 180);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'positions_battery_range'
      and conrelid = 'public.positions'::regclass
  ) then
    alter table public.positions
      add constraint positions_battery_range
      check (battery is null or battery between 0 and 100);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'positions_schema_version_range'
      and conrelid = 'public.positions'::regclass
  ) then
    alter table public.positions
      add constraint positions_schema_version_range
      check (schema_version between 1 and 255);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'positions_source_length'
      and conrelid = 'public.positions'::regclass
  ) then
    alter table public.positions
      add constraint positions_source_length
      check (length(source) between 1 and 32);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'positions_device_uid_message_id_key'
      and conrelid = 'public.positions'::regclass
  ) then
    alter table public.positions
      add constraint positions_device_uid_message_id_key
      unique (device_uid, message_id);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'positions_device_uid_fkey'
      and conrelid = 'public.positions'::regclass
  ) then
    alter table public.positions
      add constraint positions_device_uid_fkey
      foreign key (device_uid) references public.devices(device_id);
  end if;
end
$$;

create index if not exists positions_device_recorded_at_idx
  on public.positions (device_uid, recorded_at desc, message_id desc);

create index if not exists positions_recorded_at_idx
  on public.positions (recorded_at desc);

create or replace view public.latest_positions
with (security_invoker = true)
as
select distinct on (device_uid)
  id,
  device_uid,
  message_id,
  latitude,
  longitude,
  battery,
  source,
  recorded_at,
  received_at,
  schema_version
from public.positions
order by device_uid, recorded_at desc, message_id desc;

alter table public.devices enable row level security;
alter table public.device_ingest_credentials enable row level security;
alter table public.positions enable row level security;

revoke all on table public.devices from anon, authenticated;
revoke all on table public.device_ingest_credentials from anon, authenticated;
revoke insert, update, delete, truncate, references, trigger
  on table public.positions from anon, authenticated;

grant select on table public.positions to anon, authenticated, service_role;
grant select on table public.latest_positions to anon, authenticated, service_role;
grant select on table public.devices to service_role;
grant select on table public.device_ingest_credentials to service_role;
grant insert on table public.positions to service_role;

do $$
declare
  identity_sequence text;
begin
  identity_sequence := pg_get_serial_sequence('public.positions', 'id');
  if identity_sequence is not null then
    execute format('grant usage, select on sequence %s to service_role', identity_sequence);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'positions'
      and policyname = 'Temporary public read'
  ) then
    create policy "Temporary public read"
      on public.positions
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

comment on table public.devices is
  'Provisioned Bluepaws collars. device_id is an unsigned 16-bit identifier on the wire.';
comment on table public.device_ingest_credentials is
  'SHA-256 hashes of per-device ingestion bearer tokens. Never store plaintext tokens here.';
comment on view public.latest_positions is
  'Most recently recorded position for each device; runs with the caller permissions and RLS.';
