-- Add authenticated TLV telemetry while preserving the legacy JSON position
-- contract. Collar HMAC keys live in Vault; only a narrowly granted RPC can
-- use their decrypted values. Valid GNSS observations are projected into the
-- existing positions/current-position/Realtime pipeline.

set lock_timeout = '5s';
set statement_timeout = '120s';

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- Cover the existing composite device-appearance foreign key. The production
-- advisor reports it as unindexed before this migration.
create index if not exists device_appearances_device_household_idx
  on public.device_appearances (device_id, household_id);

do $$
begin
  if to_regclass('vault.secrets') is null
    or to_regclass('vault.decrypted_secrets') is null then
    raise exception 'Supabase Vault must be enabled before applying TLV ingestion';
  end if;
end
$$;

create table public.device_hmac_keys (
  device_id integer not null references public.devices(device_id) on delete cascade,
  key_version smallint not null,
  vault_secret_id uuid not null unique,
  enabled boolean not null default true,
  valid_from timestamptz not null default now(),
  valid_until timestamptz,
  created_at timestamptz not null default now(),
  primary key (device_id, key_version),
  constraint device_hmac_keys_device_range check (device_id between 1 and 65535),
  constraint device_hmac_keys_version_range check (key_version between 1 and 32767),
  constraint device_hmac_keys_valid_window check (valid_until is null or valid_until > valid_from)
);

create index device_hmac_keys_verification_idx
  on public.device_hmac_keys (device_id, enabled, valid_from, valid_until);

create table public.gateways (
  gateway_guid16 integer primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  display_name text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  constraint gateways_guid16_range check (gateway_guid16 between 1 and 65535),
  constraint gateways_display_name_length check (length(btrim(display_name)) between 1 and 80)
);

create index gateways_household_idx on public.gateways (household_id, gateway_guid16);

create table public.gateway_ingest_credentials (
  gateway_guid16 integer primary key references public.gateways(gateway_guid16) on delete cascade,
  token_hash text not null unique,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  rotated_at timestamptz,
  constraint gateway_ingest_credentials_token_hash_format
    check (token_hash ~ '^[0-9a-f]{64}$')
);

create table public.observations (
  id bigint generated by default as identity primary key,
  device_guid16 integer not null references public.devices(device_id) on delete cascade,
  household_id uuid not null references public.households(id) on delete cascade,
  protocol_version smallint not null,
  msg_seq_id integer not null,
  time_unix bigint not null,
  recorded_at timestamptz not null,
  status smallint not null,
  power_profile smallint not null,
  flags smallint not null,
  tx_reason smallint not null,
  gnss_valid boolean not null,
  latitude double precision,
  longitude double precision,
  batt_mv integer not null,
  acc_m integer not null,
  fix_age_s integer not null,
  sat_count integer not null,
  tlv_data jsonb not null default '{}'::jsonb,
  payload_hash text not null unique,
  payload_b64 text not null,
  received_at timestamptz not null default now(),
  constraint observations_device_range check (device_guid16 between 1 and 65535),
  constraint observations_protocol_version check (protocol_version = 1),
  constraint observations_sequence_range check (msg_seq_id between 0 and 65535),
  constraint observations_time_range check (time_unix between 0 and 4294967295),
  constraint observations_status_range check (status between 0 and 3),
  constraint observations_profile_range check (power_profile between 0 and 3),
  constraint observations_flags_range check (flags between 0 and 255),
  constraint observations_tx_reason_range check (tx_reason between 0 and 6),
  constraint observations_coordinates_match_flag check (
    (gnss_valid and latitude between -90 and 90 and longitude between -180 and 180)
    or (not gnss_valid and latitude is null and longitude is null)
  ),
  constraint observations_batt_mv_range check (batt_mv between 0 and 65535),
  constraint observations_acc_m_range check (acc_m between 0 and 65535),
  constraint observations_fix_age_range check (fix_age_s between 0 and 65535),
  constraint observations_sat_count_range check (sat_count between 0 and 255),
  constraint observations_tlv_object check (jsonb_typeof(tlv_data) = 'object'),
  constraint observations_payload_hash_format check (payload_hash ~ '^[0-9a-f]{64}$'),
  constraint observations_payload_b64_length check (length(payload_b64) between 56 and 88),
  constraint observations_message_identity_unique unique (device_guid16, msg_seq_id, time_unix)
);

create index observations_household_device_recorded_idx
  on public.observations (household_id, device_guid16, recorded_at desc, msg_seq_id desc);
create index observations_device_sequence_time_idx
  on public.observations (device_guid16, msg_seq_id, time_unix desc);
create index observations_recorded_at_idx on public.observations (recorded_at);

create table public.observation_paths (
  id bigint generated by default as identity primary key,
  observation_id bigint not null references public.observations(id) on delete cascade,
  household_id uuid not null references public.households(id) on delete cascade,
  route_key text not null,
  ingest_path text not null,
  link_type text not null,
  gateway_guid16 integer references public.gateways(gateway_guid16) on delete restrict,
  gateway_rx_time_unix bigint,
  link_rssi_dbm double precision,
  link_snr_db double precision,
  cell_rsrp_dbm double precision,
  cell_rsrq_db double precision,
  cell_sinr_db double precision,
  first_received_at timestamptz not null default now(),
  last_received_at timestamptz not null default now(),
  receipt_count integer not null default 1,
  constraint observation_paths_route_unique unique (observation_id, route_key),
  constraint observation_paths_route_key_length check (length(route_key) between 1 and 48),
  constraint observation_paths_ingest_path check (ingest_path in ('lora_hub', 'cellular_direct')),
  constraint observation_paths_link_type check (link_type in ('lora', 'lte')),
  constraint observation_paths_transport_pair check (
    (ingest_path = 'lora_hub' and link_type = 'lora' and gateway_guid16 is not null)
    or (ingest_path = 'cellular_direct' and link_type = 'lte' and gateway_guid16 is null)
  ),
  constraint observation_paths_gateway_time_range check (
    gateway_rx_time_unix is null or gateway_rx_time_unix between 0 and 4294967295
  ),
  constraint observation_paths_receipt_count_positive check (receipt_count > 0),
  constraint observation_paths_time_order check (last_received_at >= first_received_at)
);

create index observation_paths_household_observation_idx
  on public.observation_paths (household_id, observation_id);
create index observation_paths_gateway_idx
  on public.observation_paths (gateway_guid16, last_received_at desc)
  where gateway_guid16 is not null;

alter table public.positions
  add column observation_id bigint references public.observations(id) on delete set null,
  add column battery_mv integer,
  add column status_code smallint,
  add column power_profile_code smallint,
  add column flags integer,
  add column tx_reason smallint,
  add column link_type text,
  add column link_rssi_dbm double precision,
  add column link_snr_db double precision;

alter table public.positions
  add constraint positions_observation_id_unique unique (observation_id),
  add constraint positions_battery_mv_range check (battery_mv is null or battery_mv between 0 and 65535),
  add constraint positions_status_code_range check (status_code is null or status_code between 0 and 3),
  add constraint positions_power_profile_range check (power_profile_code is null or power_profile_code between 0 and 3),
  add constraint positions_flags_range check (flags is null or flags between 0 and 255),
  add constraint positions_tx_reason_range check (tx_reason is null or tx_reason between 0 and 6),
  add constraint positions_link_type_check check (link_type is null or link_type in ('lora', 'lte'));

alter table public.device_latest_positions
  add column observation_id bigint,
  add column battery_mv integer,
  add column status_code smallint,
  add column power_profile_code smallint,
  add column flags integer,
  add column tx_reason smallint,
  add column link_type text,
  add column link_rssi_dbm double precision,
  add column link_snr_db double precision;

alter table public.device_latest_positions
  add constraint latest_positions_battery_mv_range check (battery_mv is null or battery_mv between 0 and 65535),
  add constraint latest_positions_status_code_range check (status_code is null or status_code between 0 and 3),
  add constraint latest_positions_power_profile_range check (power_profile_code is null or power_profile_code between 0 and 3),
  add constraint latest_positions_flags_range check (flags is null or flags between 0 and 255),
  add constraint latest_positions_tx_reason_range check (tx_reason is null or tx_reason between 0 and 6),
  add constraint latest_positions_link_type_check check (link_type is null or link_type in ('lora', 'lte'));

create or replace function private.sync_latest_position()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.device_latest_positions (
    device_uid,
    household_id,
    position_id,
    message_id,
    latitude,
    longitude,
    battery,
    source,
    recorded_at,
    received_at,
    schema_version,
    observation_id,
    battery_mv,
    status_code,
    power_profile_code,
    flags,
    tx_reason,
    link_type,
    link_rssi_dbm,
    link_snr_db
  )
  values (
    new.device_uid,
    new.household_id,
    new.id,
    new.message_id,
    new.latitude,
    new.longitude,
    new.battery,
    new.source,
    new.recorded_at,
    new.received_at,
    new.schema_version,
    new.observation_id,
    new.battery_mv,
    new.status_code,
    new.power_profile_code,
    new.flags,
    new.tx_reason,
    new.link_type,
    new.link_rssi_dbm,
    new.link_snr_db
  )
  on conflict (device_uid) do update
  set
    household_id = excluded.household_id,
    position_id = excluded.position_id,
    message_id = excluded.message_id,
    latitude = excluded.latitude,
    longitude = excluded.longitude,
    battery = excluded.battery,
    source = excluded.source,
    recorded_at = excluded.recorded_at,
    received_at = excluded.received_at,
    schema_version = excluded.schema_version,
    observation_id = excluded.observation_id,
    battery_mv = excluded.battery_mv,
    status_code = excluded.status_code,
    power_profile_code = excluded.power_profile_code,
    flags = excluded.flags,
    tx_reason = excluded.tx_reason,
    link_type = excluded.link_type,
    link_rssi_dbm = excluded.link_rssi_dbm,
    link_snr_db = excluded.link_snr_db
  where
    excluded.recorded_at > public.device_latest_positions.recorded_at
    or (
      excluded.recorded_at = public.device_latest_positions.recorded_at
      and excluded.message_id > public.device_latest_positions.message_id
    );

  return new;
end;
$$;

revoke execute on function private.sync_latest_position() from public, anon, authenticated;

drop trigger if exists positions_sync_latest on public.positions;
create trigger positions_sync_latest
  after insert or update on public.positions
  for each row execute function private.sync_latest_position();

create or replace function public.ingest_tlv_observation(
  p_protocol_version smallint,
  p_device_guid16 integer,
  p_msg_seq_id integer,
  p_time_unix bigint,
  p_status smallint,
  p_power_profile smallint,
  p_flags smallint,
  p_tx_reason smallint,
  p_gnss_valid boolean,
  p_latitude double precision,
  p_longitude double precision,
  p_batt_mv integer,
  p_acc_m integer,
  p_fix_age_s integer,
  p_sat_count integer,
  p_tlv_data jsonb,
  p_payload_hash text,
  p_payload_b64 text,
  p_hmac_body_b64 text,
  p_hmac_tag_hex text,
  p_ingest_path text,
  p_link_type text,
  p_gateway_guid16 integer,
  p_gateway_rx_time_unix bigint,
  p_link_rssi_dbm double precision,
  p_link_snr_db double precision,
  p_cell_rsrp_dbm double precision,
  p_cell_rsrq_db double precision,
  p_cell_sinr_db double precision
)
returns table (
  accepted boolean,
  duplicate boolean,
  observation_id bigint,
  position_id bigint,
  received_at timestamptz,
  error_code text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_household_id uuid;
  v_observation_id bigint;
  v_position_id bigint;
  v_request_received_at timestamptz := clock_timestamp();
  v_observation_received_at timestamptz;
  v_duplicate boolean := false;
  v_route_key text;
begin
  select device.household_id
  into v_household_id
  from public.devices as device
  where device.device_id = p_device_guid16
    and device.enabled = true;

  if v_household_id is null then
    return query select false, false, null::bigint, null::bigint, v_request_received_at, 'unauthorized_device'::text;
    return;
  end if;

  if not exists (
    select 1
    from public.device_hmac_keys as device_key
    join vault.decrypted_secrets as secret
      on secret.id = device_key.vault_secret_id
    where device_key.device_id = p_device_guid16
      and device_key.enabled = true
      and device_key.valid_from <= v_request_received_at
      and (device_key.valid_until is null or device_key.valid_until > v_request_received_at)
      and substring(
        extensions.hmac(
          decode(p_hmac_body_b64, 'base64'),
          decode(secret.decrypted_secret, 'base64'),
          'sha256'
        )
        from 1 for 8
      ) = decode(p_hmac_tag_hex, 'hex')
  ) then
    return query select false, false, null::bigint, null::bigint, v_request_received_at, 'invalid_authentication'::text;
    return;
  end if;

  if exists (
    select 1
    from public.observations as existing
    where existing.device_guid16 = p_device_guid16
      and existing.msg_seq_id = p_msg_seq_id
      and existing.time_unix = p_time_unix
      and existing.payload_hash <> p_payload_hash
  ) then
    return query select false, false, null::bigint, null::bigint, v_request_received_at, 'message_identity_conflict'::text;
    return;
  end if;

  insert into public.observations (
    device_guid16,
    household_id,
    protocol_version,
    msg_seq_id,
    time_unix,
    recorded_at,
    status,
    power_profile,
    flags,
    tx_reason,
    gnss_valid,
    latitude,
    longitude,
    batt_mv,
    acc_m,
    fix_age_s,
    sat_count,
    tlv_data,
    payload_hash,
    payload_b64,
    received_at
  )
  values (
    p_device_guid16,
    v_household_id,
    p_protocol_version,
    p_msg_seq_id,
    p_time_unix,
    to_timestamp(p_time_unix),
    p_status,
    p_power_profile,
    p_flags,
    p_tx_reason,
    p_gnss_valid,
    p_latitude,
    p_longitude,
    p_batt_mv,
    p_acc_m,
    p_fix_age_s,
    p_sat_count,
    coalesce(p_tlv_data, '{}'::jsonb),
    p_payload_hash,
    p_payload_b64,
    v_request_received_at
  )
  on conflict do nothing
  returning id into v_observation_id;

  if v_observation_id is null then
    select existing.id, existing.received_at
    into v_observation_id, v_observation_received_at
    from public.observations as existing
    where existing.payload_hash = p_payload_hash;
    v_duplicate := true;
  else
    v_observation_received_at := v_request_received_at;
  end if;

  if v_observation_id is null then
    return query select false, false, null::bigint, null::bigint, v_request_received_at, 'message_identity_conflict'::text;
    return;
  end if;

  v_route_key := case
    when p_ingest_path = 'lora_hub'
      then 'lora_hub:' || lpad(to_hex(p_gateway_guid16), 4, '0')
    else 'cellular_direct'
  end;

  insert into public.observation_paths (
    observation_id,
    household_id,
    route_key,
    ingest_path,
    link_type,
    gateway_guid16,
    gateway_rx_time_unix,
    link_rssi_dbm,
    link_snr_db,
    cell_rsrp_dbm,
    cell_rsrq_db,
    cell_sinr_db,
    first_received_at,
    last_received_at,
    receipt_count
  )
  values (
    v_observation_id,
    v_household_id,
    v_route_key,
    p_ingest_path,
    p_link_type,
    p_gateway_guid16,
    p_gateway_rx_time_unix,
    p_link_rssi_dbm,
    p_link_snr_db,
    p_cell_rsrp_dbm,
    p_cell_rsrq_db,
    p_cell_sinr_db,
    v_request_received_at,
    v_request_received_at,
    1
  )
  on conflict (observation_id, route_key) do update
  set
    gateway_rx_time_unix = excluded.gateway_rx_time_unix,
    link_rssi_dbm = excluded.link_rssi_dbm,
    link_snr_db = excluded.link_snr_db,
    cell_rsrp_dbm = excluded.cell_rsrp_dbm,
    cell_rsrq_db = excluded.cell_rsrq_db,
    cell_sinr_db = excluded.cell_sinr_db,
    last_received_at = clock_timestamp(),
    receipt_count = public.observation_paths.receipt_count + 1;

  if p_gnss_valid then
    select position.id into v_position_id
    from public.positions as position
    where position.observation_id = v_observation_id;

    if v_position_id is null and not v_duplicate then
      insert into public.positions (
        device_uid,
        message_id,
        latitude,
        longitude,
        battery,
        source,
        recorded_at,
        received_at,
        schema_version,
        observation_id,
        battery_mv,
        status_code,
        power_profile_code,
        flags,
        tx_reason,
        link_type,
        link_rssi_dbm,
        link_snr_db
      )
      values (
        p_device_guid16,
        p_msg_seq_id,
        p_latitude,
        p_longitude,
        null,
        'tlv',
        to_timestamp(p_time_unix),
        v_observation_received_at,
        p_protocol_version,
        v_observation_id,
        p_batt_mv,
        p_status,
        p_power_profile,
        p_flags,
        p_tx_reason,
        p_link_type,
        p_link_rssi_dbm,
        p_link_snr_db
      )
      on conflict (device_uid, message_id) do update
      set
        latitude = excluded.latitude,
        longitude = excluded.longitude,
        battery = excluded.battery,
        source = excluded.source,
        recorded_at = excluded.recorded_at,
        received_at = excluded.received_at,
        schema_version = excluded.schema_version,
        observation_id = excluded.observation_id,
        battery_mv = excluded.battery_mv,
        status_code = excluded.status_code,
        power_profile_code = excluded.power_profile_code,
        flags = excluded.flags,
        tx_reason = excluded.tx_reason,
        link_type = excluded.link_type,
        link_rssi_dbm = excluded.link_rssi_dbm,
        link_snr_db = excluded.link_snr_db
      where public.positions.recorded_at < excluded.recorded_at
      returning id into v_position_id;
    end if;

    if v_position_id is null and v_duplicate then
      select position.id into v_position_id
      from public.positions as position
      where position.observation_id = v_observation_id;
    end if;
  end if;

  return query select true, v_duplicate, v_observation_id, v_position_id, v_request_received_at, null::text;
end;
$$;

revoke all on function public.ingest_tlv_observation(
  smallint, integer, integer, bigint, smallint, smallint, smallint, smallint,
  boolean, double precision, double precision, integer, integer, integer,
  integer, jsonb, text, text, text, text, text, text, integer, bigint,
  double precision, double precision, double precision, double precision,
  double precision
) from public, anon, authenticated;
grant execute on function public.ingest_tlv_observation(
  smallint, integer, integer, bigint, smallint, smallint, smallint, smallint,
  boolean, double precision, double precision, integer, integer, integer,
  integer, jsonb, text, text, text, text, text, text, integer, bigint,
  double precision, double precision, double precision, double precision,
  double precision
) to service_role;

alter table public.device_hmac_keys enable row level security;
alter table public.gateways enable row level security;
alter table public.gateway_ingest_credentials enable row level security;
alter table public.observations enable row level security;
alter table public.observation_paths enable row level security;

create policy "Household members read observations"
  on public.observations for select to authenticated
  using (
    exists (
      select 1 from public.household_members as member
      where member.household_id = observations.household_id
        and member.user_id = (select auth.uid())
    )
  );

create policy "Household members read observation paths"
  on public.observation_paths for select to authenticated
  using (
    exists (
      select 1 from public.household_members as member
      where member.household_id = observation_paths.household_id
        and member.user_id = (select auth.uid())
    )
  );

revoke all on table public.device_hmac_keys from public, anon, authenticated, service_role;
revoke all on table public.gateways from public, anon, authenticated, service_role;
revoke all on table public.gateway_ingest_credentials from public, anon, authenticated, service_role;
revoke all on table public.observations from public, anon, authenticated, service_role;
revoke all on table public.observation_paths from public, anon, authenticated, service_role;

grant select on table public.gateways, public.gateway_ingest_credentials to service_role;
grant select on table public.observations, public.observation_paths to authenticated;

create or replace function private.delete_expired_positions(batch_size integer default 50000)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  deleted_positions integer;
  deleted_observations integer;
begin
  delete from public.positions
  where id in (
    select id
    from public.positions
    where recorded_at < now() - interval '7 days'
    order by recorded_at
    limit greatest(1, least(batch_size, 50000))
  );
  get diagnostics deleted_positions = row_count;

  delete from public.observations
  where id in (
    select id
    from public.observations
    where recorded_at < now() - interval '7 days'
    order by recorded_at
    limit greatest(1, least(batch_size, 50000))
  );
  get diagnostics deleted_observations = row_count;

  return deleted_positions + deleted_observations;
end;
$$;

revoke execute on function private.delete_expired_positions(integer)
  from public, anon, authenticated;

comment on table public.device_hmac_keys is
  'References Base64-encoded 32-byte collar HMAC keys stored encrypted in Supabase Vault.';
comment on table public.observations is
  'Immutable authenticated collar observations, deduplicated by the full raw-packet SHA-256 hash.';
comment on table public.observation_paths is
  'Aggregated HTTPS delivery routes for an observation; retries increment receipt_count.';
comment on function public.ingest_tlv_observation(
  smallint, integer, integer, bigint, smallint, smallint, smallint, smallint,
  boolean, double precision, double precision, integer, integer, integer,
  integer, jsonb, text, text, text, text, text, text, integer, bigint,
  double precision, double precision, double precision, double precision,
  double precision
) is 'Service-role-only atomic HMAC verification and TLV observation ingestion RPC.';
