(part "EVPAA802Q"
    (packageRef "EVPAA")
    (interface
        (port "1" (symbPinId 1) (portName "NO_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "COM_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NO_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "COM_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "Panasonic")
    (property "Manufacturer_Part_Number" "EVPAA802Q")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "EVPAA802Q")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/evp-aa802q/panasonic?region=nac")
    (property "Description" "Tactile Switches Swtch Lite Touch SMD 5.0N 1.7mm ht grey")
    (property "Datasheet_Link" "https://industry.panasonic.com/ac/cdn/e/control/switch/light-touch/catalog/sw_lt_eng_3529s.pdf")
    (property "symbolName1" "EVPAA802Q")
)
